[APP]
ENVIRONMENT = "test"
DEBUG = true
FILES_DIR = ".\"


[CONFLUENCE]
# This is the URL of the Confluence API
BASE_URL = "http://jira.dirhu.techint.net:8090/confluence/rest/api/content"
# This is the URL to convert content from the Confluence API
CONVERT_URL = "http://jira.dirhu.techint.net:8090/confluence/rest/api/contentbody/convert"
# This is the URL to view a page (only to show in the script output)
VIEW_URL = "http://jira.dirhu.techint.net:8090/confluence/pages/viewpage.action?pageId="
# Key of the Confluence Space
SPACE_CONF = 'CLC'
# Conection user
USER_CONF = 'BAISCF'
# Father page id to add other pages
PAG_PADRE_CONF = "21235169"
# Template page id to use when adding pages
PAG_TEMPLATE = "21240001"
# User agent for the API call
USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36"
